"""add stock control to alimentos

Revision ID: 3e3c9e88e9fa
Revises: 5e4eabd3d8a0
Create Date: 2026-09-12 20:05:35.981852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e3c9e88e9fa'
down_revision: Union[str, None] = '5e4eabd3d8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'ajuste', name='tipo_movimiento_stock'), nullable=False),
    sa.Column('cantidad_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alimentos', sa.Column('stock_actual_kg', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('alimentos', sa.Column('stock_minimo_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alimentos', 'stock_minimo_kg')
    op.drop_column('alimentos', 'stock_actual_kg')
    op.drop_table('movimientos_stock')
    # ### end Alembic commands ###
