"""init

Revision ID: 99f6978b3407
Revises: 
Create Date: 2026-09-12 19:28:23.788293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '99f6978b3407'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('caravana_color', sa.String(length=60), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('peso_inicial_promedio', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'cerrado', name='estado_lote'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'operario', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('animales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caravana', sa.String(length=60), nullable=False),
    sa.Column('caravana_provisoria', sa.Boolean(), nullable=False),
    sa.Column('sexo', sa.Enum('macho', 'hembra', name='sexo_animal'), nullable=False),
    sa.Column('caracteristicas', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_destete', sa.Date(), nullable=True),
    sa.Column('madre', sa.String(length=60), nullable=True),
    sa.Column('padre', sa.String(length=60), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'vendido', 'baja', name='estado_animal'), nullable=False),
    sa.Column('peso_destete_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animales_caravana'), 'animales', ['caravana'], unique=True)
    op.create_table('consumos_reales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('alimento', sa.String(length=120), nullable=False),
    sa.Column('cantidad_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_alimentacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=120), nullable=False),
    sa.Column('dia_desde', sa.Integer(), nullable=False),
    sa.Column('dia_hasta', sa.Integer(), nullable=False),
    sa.Column('pct_consumo_pv', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('adpv_esperado_kg', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('costo_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pesajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id', 'fecha', name='uq_pesaje_animal_fecha')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=False),
    sa.Column('peso_venta_kg', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('precio_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comprador', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('pesajes')
    op.drop_table('plan_alimentacion')
    op.drop_table('consumos_reales')
    op.drop_index(op.f('ix_animales_caravana'), table_name='animales')
    op.drop_table('animales')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('lotes')
    # ### end Alembic commands ###
